[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-lobbyguard"
version = "1.0.0"
description = "Simple lobby protection for EndstoneMC."
readme = "README.md"
requires-python = ">=3.10"

[project.entry-points."endstone"]
lobbyguard = "lobbyguard.main:LobbyGuard"

[tool.hatch.build.targets.wheel]
packages = ["src/lobbyguard"]
